--What is the total revenue generated by each product category?
select * from products;
select * from order_items;
select * from categories;
select * from orders;
select * from customer;
select distinct(product_name) from products;

select c.category_name,round(sum(o.list_price*o.quantity*(1-o.discount))::numeric,2) as revenue
from  products p
join order_items o
on p.product_id=o.product_id
join categories c
on c.category_id=p.category_id
group by c.category_name
order by revenue desc;

--Who are the top 10 customers by total order value?

--Identify the customers who have spent the most. 

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.state,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.list_price * oi.quantity * (1 - oi.discount))::numeric, 2) AS total_order_value
FROM 
    customer c
JOIN 
    orders o ON c.customer_id = o.customer_id
JOIN 
    order_items oi ON o.order_id = oi.order_id
GROUP BY 
    c.customer_id, c.first_name, c.last_name, c.state
ORDER BY 
    total_order_value DESC
LIMIT 10;


--What are the total revenue and quantity sold per year?

--Assess annual sales trends to identify growth or decline

SELECT 
    EXTRACT(YEAR FROM o.order_date::date) AS year,
    ROUND(SUM(oi.list_price * oi.quantity * (1 - oi.discount))::numeric, 2) AS total_revenue,
    SUM(oi.quantity) AS total_quantity_sold
FROM 
    orders o
JOIN 
    order_items oi ON o.order_id = oi.order_id
GROUP BY 
    year
ORDER BY 
    year;


--Which customers have not placed any orders in the past year?

--Identify inactive customers for re-engagement strategies.

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    c.email,
    c.state
FROM 
    customer c
LEFT JOIN 
    orders o 
    ON c.customer_id = o.customer_id 
    AND o.order_date::date >= CURRENT_DATE - INTERVAL '1 year'
WHERE 
    o.order_id IS NULL;



--Which products are the top 10 by total sales?

--Determine the best-selling products


SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM 
    products p
JOIN 
    order_items oi ON p.product_id = oi.product_id
GROUP BY 
    p.product_name
ORDER BY 
    total_quantity_sold DESC
LIMIT 10;


--What is the total revenue by brand?

--Evaluate brand performance based on sales.

SELECT 
    b.brand_name,
    ROUND(SUM(oi.quantity * oi.list_price * (1 - oi.discount))::numeric, 2) AS total_revenue
FROM 
    brands b
JOIN 
    products p ON b.brand_id = p.brand_id
JOIN 
    order_items oi ON p.product_id = oi.product_id
GROUP BY 
    b.brand_name
ORDER BY 
    total_revenue DESC;


--Which customers have placed more than two orders?

--Identify loyal customers for potential loyalty programs

SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    c.email,
    COUNT(o.order_id) AS order_count
FROM 
    customer c
JOIN 
    orders o ON c.customer_id = o.customer_id
GROUP BY 
    c.customer_id, c.first_name, c.last_name, c.email
HAVING 
    COUNT(o.order_id) > 2
ORDER BY 
    order_count DESC;


--Top Customers by Revenue in Each State

WITH CustomerStateRevenue AS (
    SELECT
        c.customer_id,
        c.state,
        SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
    FROM
        customer c
    JOIN
        orders o ON c.customer_id = o.customer_id
    JOIN
        order_items oi ON o.order_id = oi.order_id
    GROUP BY
        c.customer_id, c.state
)
SELECT
    customer_id,
    state,
    total_revenue
FROM (
    SELECT
        customer_id,
        state,
        total_revenue,
        RANK() OVER (PARTITION BY state ORDER BY total_revenue DESC) AS revenue_rank
    FROM
        CustomerStateRevenue
) AS ranked_customers
WHERE
    revenue_rank <= 5
ORDER BY
    state, revenue_rank;


--Identifying Products Low in Stock Across All Stores

SELECT
    p.product_id,
    p.product_name,
    SUM(s.quantity) AS total_stock
FROM
    products p
JOIN
    stocks s ON p.product_id = s.product_id
GROUP BY
    p.product_id, p.product_name
HAVING
    SUM(s.quantity) < 10; 

-- Calculating Product Turnover Rate Based on Sales and Stock

SELECT
    p.product_id,
    p.product_name,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_sales,
    AVG(s.quantity) AS avg_inventory,
    CASE
        WHEN AVG(s.quantity) = 0 THEN NULL
        ELSE SUM(oi.quantity * oi.list_price * (1 - oi.discount)) / AVG(s.quantity)
    END AS turnover_rate
FROM
    products p
JOIN
    order_items oi ON p.product_id = oi.product_id
JOIN
    stocks s ON p.product_id = s.product_id
GROUP BY
    p.product_id, p.product_name;

-- Identifying Stores with Highest and Lowest Stock Levels by Product


SELECT
    p.product_id,
    p.product_name,
    s.store_id,
    st.store_name,
    s.quantity AS stock_level,
    RANK() OVER (PARTITION BY p.product_id ORDER BY s.quantity DESC) AS stock_rank_desc,
    RANK() OVER (PARTITION BY p.product_id ORDER BY s.quantity ASC) AS stock_rank_asc
FROM
    products p
JOIN
    stocks s ON p.product_id = s.product_id
JOIN
    stores st ON s.store_id = st.store_id;


--Calculating Average Time Between Order Placement and Shipment for Each Product

SELECT
    p.product_name,
    ROUND(AVG(EXTRACT(EPOCH FROM (CAST(o.shipped_date AS timestamp) - CAST(o.order_date AS timestamp))) / 86400), 2) AS avg_shipping_days
FROM
    products p
JOIN
    order_items oi ON p.product_id = oi.product_id
JOIN
    orders o ON oi.order_id = o.order_id
WHERE
    o.shipped_date IS NOT NULL
GROUP BY
    p.product_name
ORDER BY
    avg_shipping_days ASC;

